# Generated by Django 5.1.2 on 2024-11-09 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctoralStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=100)),
                ('semesters', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], max_length=100, null=True)),
                ('school_year', models.CharField(choices=[('1972-1973', '1972-1973'), ('1973-1974', '1973-1974'), ('1974-1975', '1974-1975'), ('1975-1976', '1975-1976'), ('1976-1977', '1976-1977'), ('1977-1978', '1977-1978'), ('1978-1979', '1978-1979'), ('1979-1980', '1979-1980'), ('1980-1981', '1980-1981'), ('1981-1982', '1981-1982'), ('1982-1983', '1982-1983'), ('1983-1984', '1983-1984'), ('1984-1985', '1984-1985'), ('1985-1986', '1985-1986'), ('1986-1987', '1986-1987'), ('1987-1988', '1987-1988'), ('1988-1989', '1988-1989'), ('1989-1990', '1989-1990'), ('1990-1991', '1990-1991'), ('1991-1992', '1991-1992'), ('1992-1993', '1992-1993'), ('1993-1994', '1993-1994'), ('1994-1995', '1994-1995'), ('1995-1996', '1995-1996'), ('1996-1997', '1996-1997'), ('1997-1998', '1997-1998'), ('1998-1999', '1998-1999'), ('1999-2000', '1999-2000'), ('2000-2001', '2000-2001'), ('2001-2002', '2001-2002'), ('2002-2003', '2002-2003'), ('2003-2004', '2003-2004'), ('2004-2005', '2004-2005'), ('2005-2006', '2005-2006'), ('2006-2007', '2006-2007'), ('2007-2008', '2007-2008'), ('2008-2009', '2008-2009'), ('2009-2010', '2009-2010'), ('2010-2011', '2010-2011'), ('2011-2012', '2011-2012'), ('2012-2013', '2012-2013'), ('2013-2014', '2013-2014'), ('2014-2015', '2014-2015'), ('2015-2016', '2015-2016'), ('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], max_length=100, null=True)),
                ('programs', models.CharField(choices=[('Master of Arts in Education', 'Master of Arts in Education'), ('Master of Management', 'Master of Management')], max_length=50, null=True)),
                ('student_type', models.CharField(choices=[('Freshman', 'Freshman'), ('Transferee', 'Transferee'), ('Returnee', 'Returnee'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Finishing', 'Finishing'), ('Foreign', 'Foreign')], max_length=100, null=True)),
                ('majors', models.CharField(choices=[('Educational Management', 'Educational Management'), ('Elementary Education', 'Elementary Education'), ('Technology Education', 'Technology Education'), ('Home Economics', 'Home Economics'), ('Industrial Education', 'Industrial Education'), ('English', 'English'), ('Filipino', 'Filipino'), ('Physical Education', 'Physical Education'), ('Mathematics', 'Mathematics'), ('Marine Engineering & Nautical Science', 'Marine Engineering & Nautical Science'), ('Science', 'Science')], max_length=100, null=True)),
                ('statistics_score', models.IntegerField(blank=True, null=True)),
                ('philo_score', models.IntegerField(blank=True, null=True)),
                ('research_score', models.IntegerField(blank=True, null=True)),
                ('major_score', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctoralStudentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('comprehensive_exam', 'Comprehensive Exam'), ('TOR', 'TOR'), ('evaluation_of_grades', 'Evaluation of Grades'), ('subject_load', 'Subject Load'), ('thesis', 'Thesis')], max_length=100)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='CGS_Records.doctoralstudents')),
            ],
        ),
    ]
