# Generated by Django 5.1.2 on 2024-11-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0002_alter_doctoralstudents_majors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoralstudents',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='DoctoralStudentFile',
        ),
    ]
