# Generated by Django 5.1.2 on 2024-11-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0004_comprehensiveexam_evaluationofgrades_subjectload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comprehensiveexam',
            name='file',
        ),
        migrations.RemoveField(
            model_name='evaluationofgrades',
            name='file',
        ),
        migrations.RemoveField(
            model_name='subjectload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='file',
        ),
        migrations.RemoveField(
            model_name='tor',
            name='file',
        ),
        migrations.AddField(
            model_name='comprehensiveexam',
            name='files',
            field=models.ManyToManyField(related_name='comprehensive_exams', to='CGS_Records.file'),
        ),
        migrations.AddField(
            model_name='evaluationofgrades',
            name='files',
            field=models.ManyToManyField(related_name='evaluation_of_grades', to='CGS_Records.file'),
        ),
        migrations.AddField(
            model_name='subjectload',
            name='files',
            field=models.ManyToManyField(related_name='subject_loads', to='CGS_Records.file'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='files',
            field=models.ManyToManyField(related_name='theses', to='CGS_Records.file'),
        ),
        migrations.AddField(
            model_name='tor',
            name='files',
            field=models.ManyToManyField(related_name='tor_files', to='CGS_Records.file'),
        ),
    ]
