# Generated by Django 5.1.2 on 2024-11-11 06:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0005_file_remove_comprehensiveexam_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationofgrades',
            name='files',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='files',
        ),
        migrations.RemoveField(
            model_name='tor',
            name='files',
        ),
        migrations.RemoveField(
            model_name='comprehensiveexam',
            name='files',
        ),
        migrations.RemoveField(
            model_name='subjectload',
            name='files',
        ),
        migrations.RemoveField(
            model_name='comprehensiveexam',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='evaluationofgrades',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='subjectload',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='tor',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='comprehensiveexam',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/comprehensive_exams/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationofgrades',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/evaluation_grades/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectload',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/subject_load/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thesis',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/thesis/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tor',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/tor/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluationofgrades',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_grades', to='CGS_Records.doctoralstudents'),
        ),
        migrations.AlterField(
            model_name='subjectload',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_load', to='CGS_Records.doctoralstudents'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_files', to='CGS_Records.doctoralstudents'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
