# Generated by Django 5.1.2 on 2024-11-14 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0007_masteralstudents_masteralevaluationofgrades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteralcomprehensiveexam',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
