# Generated by Django 5.1.2 on 2024-11-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0009_comprehensiveexam_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprehensiveexam',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationofgrades',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='masteralcomprehensiveexam',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='masteralevaluationofgrades',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='masteralsubjectload',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='masteralthesis',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='masteraltor',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subjectload',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tor',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
