# Generated by Django 5.1.2 on 2024-11-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0012_alter_faculty_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoralstudents',
            name='semesters',
            field=models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', 'Summer')], max_length=100),
        ),
    ]
