# Generated by Django 5.1.2 on 2024-11-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0013_alter_doctoralstudents_semesters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoralstudents',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='masteralstudents',
            name='sex',
        ),
        migrations.AddField(
            model_name='doctoralstudents',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='masteralstudents',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=100),
        ),
    ]
