# Generated by Django 5.1.2 on 2024-11-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0014_remove_doctoralstudents_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoralstudents',
            name='majors',
            field=models.CharField(blank=True, choices=[('Educational Management', 'Educational Management'), ('Elementary Education', 'Elementary Education'), ('Technology Education', 'Technology Education'), ('Home Economics', 'Home Economics'), ('Industrial Education', 'Industrial Education'), ('English', 'English'), ('Filipino', 'Filipino'), ('Physical Education', 'Physical Education'), ('Mathematics', 'Mathematics'), ('Marine Engineering & Nautical Science', 'Marine Engineering  and Nautical Science'), ('Science', 'Science')], max_length=100),
        ),
    ]
