# Generated by Django 5.1.2 on 2024-11-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0016_alter_doctoralstudents_majors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty_Researches',
        ),
    ]
