# Generated by Django 5.1.2 on 2024-11-22 11:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0017_delete_faculty_researches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Curriculumn_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/faculty_curriculumn/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.CharField(blank=True, max_length=20, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_curriculumn', to='CGS_Records.faculty')),
            ],
        ),
    ]
