# Generated by Django 5.1.2 on 2024-11-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0018_faculty_curriculumn_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoralstudents',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile_pictures/'),
        ),
    ]
