# Generated by Django 5.1.2 on 2024-11-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0020_masteralstudents_mprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='fprofile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/faculty_profile_pictures/'),
        ),
    ]
