# Generated by Django 5.1.2 on 2024-11-23 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0023_alter_masteralstudents_semesters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/Loa/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.CharField(blank=True, max_length=20, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loa_files', to='CGS_Records.doctoralstudents')),
            ],
        ),
        migrations.DeleteModel(
            name='Thesis',
        ),
    ]
