# Generated by Django 5.1.2 on 2024-11-23 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0024_loa_delete_thesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasteralLoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/masteral_loa/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.CharField(blank=True, max_length=20, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteral_loa_files', to='CGS_Records.masteralstudents')),
            ],
        ),
        migrations.DeleteModel(
            name='MasteralThesis',
        ),
    ]
