# Generated by Django 5.1.2 on 2024-11-23 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0025_masteralloa_delete_masteralthesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasteralPromissory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/masteral_promissory_files/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.CharField(blank=True, max_length=20, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteral_promissory_files', to='CGS_Records.masteralstudents')),
            ],
        ),
        migrations.CreateModel(
            name='Promissory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/promissory_files/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.CharField(blank=True, max_length=20, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promissory_files', to='CGS_Records.doctoralstudents')),
            ],
        ),
    ]
