# Generated by Django 5.1.2 on 2024-11-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0026_masteralpromissory_promissory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promissory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promissory', to='CGS_Records.doctoralstudents'),
        ),
    ]
