# Generated by Django 5.1.2 on 2024-11-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0027_alter_promissory_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteralpromissory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteral_promissory', to='CGS_Records.masteralstudents'),
        ),
    ]
