# Generated by Django 5.1.2 on 2024-11-27 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0028_alter_masteralpromissory_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoralstudents',
            name='majors',
        ),
    ]
