# Generated by Django 5.1.2 on 2024-11-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0030_alter_doctoralstudents_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoralstudents',
            name='student_type',
            field=models.CharField(blank=True, choices=[('Freshman', 'Freshman'), ('Old', 'Old'), ('Transferee', 'Transferee'), ('Returnee', 'Returnee'), ('Continuing', 'Continuing'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Finishing', 'Finishing'), ('Foreign', 'Foreign')], max_length=100),
        ),
        migrations.AlterField(
            model_name='masteralstudents',
            name='student_type',
            field=models.CharField(blank=True, choices=[('Freshman', 'Freshman'), ('Old', 'Old'), ('Transferee', 'Transferee'), ('Returnee', 'Returnee'), ('Continuing', 'Continuing'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Finishing', 'Finishing'), ('Foreign', 'Foreign')], max_length=100),
        ),
    ]
