# Generated by Django 5.1.2 on 2024-11-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0032_alter_doctoralstudents_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoralstudents',
            name='programs',
            field=models.CharField(blank=True, choices=[('PhD. Education.', 'PhD. Education'), ('Doctor of Management', 'Doctor of Management')], max_length=50),
        ),
    ]
