# Generated by Django 5.1.2 on 2024-11-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0033_alter_doctoralstudents_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoralstudents',
            name='programs',
            field=models.CharField(blank=True, choices=[('PhD. Education', 'PhD. Education'), ('PhD. Technology Management', 'PhD. Technology Management'), ('Doctor of Management', 'Doctor of Management')], max_length=50),
        ),
    ]
