# Generated by Django 5.1.2 on 2024-11-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0034_alter_doctoralstudents_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoralstudents',
            name='programs',
            field=models.CharField(blank=True, choices=[('PhD.  Education Major in Educational Management', 'PhD.  Education Major in Educational Management'), ('PhD. in Technology Management', 'PhD. in Technology Management'), ('Doctor of Management', 'Doctor of Management')], max_length=50),
        ),
    ]
