# Generated by Django 5.1.2 on 2024-12-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0035_alter_doctoralstudents_programs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluationOfGrades',
        ),
    ]
