# Generated by Django 5.1.2 on 2024-12-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGS_Records', '0039_alter_masteralstudents_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoralstudents',
            name='student_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Old', 'Old')], max_length=100),
        ),
        migrations.AlterField(
            model_name='masteralstudents',
            name='student_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Old', 'Old')], max_length=100),
        ),
    ]
