# Generated by Django 5.1.1 on 2024-10-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
